### ISSUE TITLE
Pulling wrong package from npm

### ISSUE THREAD

**Issue by DavidStummer** [thekevinbrown/react-native-schemes-manager#69]
### Steps to reproduce the behavior
yarn add react-native-schemes-manager:
<img width="393" alt="Screenshot 2019-04-02 at 08 30 42" src="https://user-images.githubusercontent.com/4497624/55386969-7fa3ba00-5528-11e9-9ff1-29b93c17da1b.png">

### Expected behavior
yarn to pull the latest code from github repo

### Actual behavior
yarn pulls from a different, outdated repo, as demonstrated in the package.json:
<img width="740" alt="Screenshot 2019-04-02 at 08 33 53" src="https://user-images.githubusercontent.com/4497624/55387014-977b3e00-5528-11e9-90b9-a874f643f1d5.png">

**Comment by thekevinbrown** [comment]
I've just published v2.0.0 with the new git repo URL in the package.json file which should resolve this issue for you. Please let me know if you have any further trouble with this!

**Comment by DavidStummer** [comment]
Thanks, great project!
