### ISSUE TITLE
Using this package for Whitelabel project?!

### ISSUE THREAD

**Issue by strdr4605** [thekevinbrown/react-native-schemes-manager#82]
I am working on a Whitelabel project with planned 50+ apps. Creating new targets/schemes is a lot of manual work. So I am looking to automate this. 

Reading:
> The package is able to do three things:
> - Swap its own version of react-native-xcode.sh in instead of the stock one that assumes all debug schemes are named 'Debug'.
> - Add your build configurations to all library Xcode projects.
> - Hide any schemes that come from your library projects so they don't show up in the menu.

I don't fully understand the purpose of this package and how it can help with my problem.

This is why I am asking: 
**Will this package help me to reduce my manual work on creating new apps every other week??**

**Comment by thekevinbrown** [comment]
No, it won't.

The purpose of this project was to enable React Native to show the debugging menu when using a scheme that wasn't called "Debug". That required a lot of reading through xcode files and tweaking things before React Native 0.60, but is now no longer required.
